language: python
python:
  - "3.7-dev"
install:
  - pip install -r requirements.txt
  - pip install -U pytest
  - pip install codecov
script:
  - pytest poptimizer -v --cov=poptimizer --cov-report=term-missing --setup-show
after_success:
  - codecov
