language: python
python:
- "3.6"
install:
- pip install -r requirements.txt
- pip install codecov
script:
  - pytest poptimizer -v --cov=poptimizer --cov-report=term-missing --setup-show
after_success:
  - codecov
